spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_clinic_prod
    username: pet_clinic_prod_user
    password: $PET_CLINIC_PROD_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false