spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_clinic_dev
    username: pet_clinic_dev_user
    password: $PET_CLINIC_DEV_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database-schema.sql